### ISSUE TITLE
version number and folder name don't match

### ISSUE THREAD

**Issue by dietmarw** [kdavies4/FCSys#7]
I noticed that the version annotation is at 0.2.3 but the folder is still called "FCSys 0.2". This should be corrected to "FCSys 0.2.3" and upwards for the future in order to be according to the specification.

**Comment by kdavies4** [comment]
Ok.  Maybe I misunderstood your email 06/17/2013 05:10 PM about that.  I'll take care of it.  I'm surprised that the "bug fix" part of the version number (according to semver) needs to be included in the folder name.

**Comment by dietmarw** [comment]
This is basically an issue of the Modelica Specification which does not yet know of SemVer really.

**Comment by kdavies4** [comment]
This is addressed in b33ba8d.  The next release will have the full version number in the folder name.
